### ISSUE TITLE
Certificate issuer should be configurable and possibly configured

### ISSUE THREAD

**Issue by landerlini** [landerlini/interlink-condorce-plugin#4]
The certification of the endpoint is assumed to be managed by other services in the cluster because interlink has a path ingress.
However the `Issuer` should be configurable (rather than being simply `lets-issuer`) and deployed if `certificateManagerEnabled` is true.

https://github.com/landerlini/interlink-condorce-plugin/blob/e9a81180889f3982ab4c6abb456104821a28d868/charts/interlink-all-in-one/templates/nats.yaml#L138

A ClusterIssue known to work is the following
```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-issuer
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: l.anderlini@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx

```
