### ISSUE TITLE
NOTES.txt should include a template for a LocalQueue

### ISSUE THREAD

**Issue by landerlini** [landerlini/interlink-condorce-plugin#5]
A LocalQueue is necessary to bridge the gap between the namespace and the ClusterQueue. 
While it shouldn't be deployed automatically, a template should be provided in NOTES.txt

```yaml
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  namespace: 
  name: 
spec:
  clusterQueue: 

```
